"""add building name col

Revision ID: 04d18988d2be
Revises: a7c0c9e6dc6a
Create Date: 2023-10-21 16:40:11.596649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04d18988d2be'
down_revision: Union[str, None] = 'a7c0c9e6dc6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('building', 'name')
    # ### end Alembic commands ###
