"""init db

Revision ID: 4d01cfc5e747
Revises: 
Create Date: 2023-10-10 04:41:03.742385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d01cfc5e747'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('building',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('capacity', sa.String(), nullable=True),
    sa.Column('busyness', sa.String(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('input',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('busyness', sa.String(), nullable=False),
    sa.Column('building_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room',
    sa.Column('building_id', sa.Uuid(), nullable=False),
    sa.Column('room_number', sa.Integer(), nullable=False),
    sa.Column('busyness', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['building.id'], ),
    sa.PrimaryKeyConstraint('building_id', 'room_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room')
    op.drop_table('input')
    op.drop_table('building')
    # ### end Alembic commands ###
